version: '3'
services:
  influx:
    image: influxdb:alpine
    container_name: influx
    ports:
      - "8086:8086"
      - "2003:2003"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 'true'
    volumes:
      - ./influxdb:/var/lib/influxdb:rw

  zoo1:
      image: "zookeeper:latest"
      ports:
        - "2181:2181"
      environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo2:
      image: "zookeeper:latest"
      ports:
        - "2182:2181"
      environment:
        ZOO_MY_ID: 2
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  zoo3:
      image: "zookeeper:latest"
      ports:
        - "2183:2181"
      environment:
        ZOO_MY_ID: 3
        ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  kafka1:
    image: "wurstmeister/kafka:latest"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181

  kafka2:
    image: "wurstmeister/kafka:latest"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181

  kafka3:
    image: "wurstmeister/kafka:latest"
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181

  telegraf_publisher:
    image: telegraf:alpine
    container_name: telegraf_publisher
    depends_on:
      - influx
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - ./telegraf-publisher.conf:/etc/telegraf/telegraf.conf:ro

  telegraf_consumer:
    image: telegraf:alpine
    container_name: telegraf_consumer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    volumes:
      - ./telegraf-consumer.conf:/etc/telegraf/telegraf.conf:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influx
    volumes:
     - ./grafana:/var/lib/grafana:rw
